package com.tvrepairkathmandu.trkyoutube;

import android.app.Activity;
import android.os.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.*;
import android.content.*;
import android.content.res.Configuration;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.webkit.*;
import android.widget.*;
import java.util.*;
import com.google.zxing.*;
import com.google.zxing.common.BitMatrix;

public class MainActivity extends Activity {
 private static final String VERSION="0.3.1"; private SharedPreferences prefs; private WebView web; private EditText search; private LinearLayout content;
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);} private int sw(){return getResources().getConfiguration().screenWidthDp;}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("trk_youtube",0);immersive();showWelcome();}
 private void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894);}
 private TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(dp(10),dp(6),dp(10),dp(6));return v;}
 private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private Button b(String s){Button v=new Button(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sw()<700?14:16);v.setAllCaps(false);v.setSingleLine(true);v.setEllipsize(android.text.TextUtils.TruncateAt.END);v.setFocusable(true);v.setBackgroundResource(R.drawable.focus_bg);return v;}
 private void showWelcome(){destroyWeb();ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);int p=dp(sw()<700?24:54);root.setPadding(p,dp(28),p,dp(28));root.setBackgroundColor(Color.rgb(12,12,12));sc.addView(root);TextView logo=t("▶  TRK YouTube TV",sw()<700?28:34);logo.setTypeface(null,1);root.addView(logo);root.addView(t("Watch YouTube on old & new Android TVs",18));root.addView(t("v"+VERSION+"  •  Android 4.4+",14));Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,dp(20)));Button guest=b("WATCH AS GUEST");guest.setOnClickListener(v->{prefs.edit().putBoolean("guest",true).apply();showHome();});root.addView(guest,new LinearLayout.LayoutParams(dp(420),dp(62)));Button signin=b("SIGN IN WITH PHONE");signin.setOnClickListener(v->showSignIn());root.addView(signin,new LinearLayout.LayoutParams(dp(420),dp(62)));Button browser=b("USE YOUTUBE IN BROWSER");browser.setOnClickListener(v->openWeb("https://www.youtube.com/"));root.addView(browser,new LinearLayout.LayoutParams(dp(420),dp(62)));setContentView(sc);guest.requestFocus();}
 private void showHome(){destroyWeb();LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.HORIZONTAL);shell.setPadding(dp(12),dp(12),dp(12),dp(12));shell.setBackgroundColor(Color.rgb(10,10,10));int navW=sw()<700?dp(170):dp(220);LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.VERTICAL);nav.setPadding(dp(2),dp(4),dp(8),dp(4));TextView logo=t("▶ TRK",22);logo.setTypeface(null,1);nav.addView(logo);addNav(nav,"⌂  Home",v->showHome());addNav(nav,"⌕  Search",v->{if(search!=null)search.requestFocus();});addNav(nav,"🔥  Explore",v->openWeb("https://www.youtube.com/feed/trending"));addNav(nav,"▣  Subscriptions",v->openWeb("https://www.youtube.com/feed/subscriptions"));addNav(nav,"◷  History",v->openWeb("https://www.youtube.com/feed/history"));addNav(nav,"★  Favorites",v->showLocal());addNav(nav,"☺  Account",v->showAccount());addNav(nav,"⚙  Settings",v->showSettings());shell.addView(nav,new LinearLayout.LayoutParams(navW,-1));ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),dp(2),dp(8),dp(24));sc.addView(content);shell.addView(sc,new LinearLayout.LayoutParams(0,-1,1));LinearLayout top=new LinearLayout(this);search=new EditText(this);search.setSingleLine();search.setHint("Search YouTube");search.setHintTextColor(Color.LTGRAY);search.setTextColor(Color.WHITE);search.setTextSize(17);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);search.setBackground(bg(Color.rgb(38,38,38),22));search.setOnEditorActionListener((v,a,e)->{doSearch();return true;});top.addView(search,new LinearLayout.LayoutParams(0,dp(54),1));Button go=b("SEARCH");go.setOnClickListener(v->doSearch());top.addView(go,new LinearLayout.LayoutParams(dp(110),dp(54)));content.addView(top);TextView title=t("Recommended for you",sw()<700?23:27);title.setTypeface(null,1);content.addView(title);addRow("Start watching",new String[]{"Search videos","Trending now","Music","News","Live"},new String[]{"search","https://www.youtube.com/feed/trending","https://www.youtube.com/results?search_query=music","https://www.youtube.com/results?search_query=news","https://www.youtube.com/results?search_query=live"});addRow("Explore",new String[]{"Movies & TV","Gaming","Sports","Learning","Podcasts"},new String[]{"https://www.youtube.com/results?search_query=movies","https://www.youtube.com/gaming","https://www.youtube.com/results?search_query=sports","https://www.youtube.com/results?search_query=learning","https://www.youtube.com/podcasts"});addRow("Your TRK library",new String[]{"Watch history","Favorites","Subscriptions","YouTube library"},new String[]{"https://www.youtube.com/feed/history","local","https://www.youtube.com/feed/subscriptions","https://www.youtube.com/feed/you"});setContentView(shell);nav.getChildAt(1).requestFocus();}
 private void addNav(LinearLayout n,String s,View.OnClickListener l){Button x=b(s);x.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);x.setOnClickListener(l);n.addView(x,new LinearLayout.LayoutParams(-1,dp(52)));}
 private void addRow(String h,String[] names,String[] urls){TextView x=t(h,20);x.setTypeface(null,1);content.addView(x);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);int cw=dp(sw()<700?185:225);for(int i=0;i<names.length;i++){final String u=urls[i];LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(5),dp(5),dp(5),dp(5));TextView art=t("▶",34);art.setGravity(Gravity.CENTER);art.setBackground(bg(Color.rgb(35,35,35),12));card.addView(art,new LinearLayout.LayoutParams(cw,dp(105)));Button name=b(names[i]);name.setOnClickListener(v->{if("search".equals(u))search.requestFocus();else if("local".equals(u))showLocal();else openWeb(u);});card.addView(name,new LinearLayout.LayoutParams(cw,dp(52)));row.addView(card);}hs.addView(row);content.addView(hs,new LinearLayout.LayoutParams(-1,dp(175)));}
 private void doSearch(){String q=search.getText().toString().trim();if(q.length()>0)openWeb("https://www.youtube.com/results?search_query="+Uri.encode(q));}
 private void setupWeb(){destroyWeb();web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setLoadWithOverviewMode(true);s.setUseWideViewPort(true);if(Build.VERSION.SDK_INT>=21)CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient());}
 private void openWeb(String url){setupWeb();LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.BLACK);LinearLayout bar=new LinearLayout(this);Button home=b("⌂ HOME");home.setOnClickListener(v->showHome());bar.addView(home,new LinearLayout.LayoutParams(dp(125),dp(50)));Button back=b("← BACK");back.setOnClickListener(v->{if(web.canGoBack())web.goBack();else showHome();});bar.addView(back,new LinearLayout.LayoutParams(dp(110),dp(50)));bar.addView(t("YouTube",16),new LinearLayout.LayoutParams(0,dp(50),1));r.addView(bar);r.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);web.loadUrl(url);}
 private void showSignIn(){LinearLayout r=page();TextView h=t("Sign in",sw()<700?26:30);h.setTypeface(null,1);r.addView(h);r.addView(t("Sign in with your phone",21));r.addView(t("Scan with your phone. TRK never asks for your Google password.",16));LinearLayout qrLine=new LinearLayout(this);qrLine.setGravity(Gravity.CENTER_VERTICAL);ImageView qr=new ImageView(this);qr.setImageBitmap(qr("https://www.youtube.com/activate",220));qrLine.addView(qr,new LinearLayout.LayoutParams(dp(220),dp(220)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(18),0,0,0);info.addView(t("youtube.com/activate",20));info.addView(t("Account connection is not activated yet because a Google TV OAuth client ID is still required. Guest mode and browser sign-in work now.",15));qrLine.addView(info,new LinearLayout.LayoutParams(0,-2,1));r.addView(qrLine);Button open=b("OPEN YOUTUBE SIGN-IN");open.setOnClickListener(v->openWeb("https://www.youtube.com/activate"));r.addView(open,new LinearLayout.LayoutParams(-1,dp(58)));Button guest=b("WATCH AS GUEST");guest.setOnClickListener(v->showHome());r.addView(guest,new LinearLayout.LayoutParams(-1,dp(58)));Button back=b("← BACK");back.setOnClickListener(v->showWelcome());r.addView(back,new LinearLayout.LayoutParams(-1,dp(58)));open.requestFocus();}
 private Bitmap qr(String data,int sizeDp){int size=dp(sizeDp);try{BitMatrix m=new MultiFormatWriter().encode(data,BarcodeFormat.QR_CODE,size,size);Bitmap bm=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int y=0;y<size;y++)for(int x=0;x<size;x++)bm.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);return bm;}catch(Exception e){return Bitmap.createBitmap(1,1,Bitmap.Config.RGB_565);}}
 private LinearLayout page(){ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);int p=dp(sw()<700?28:54);r.setPadding(p,dp(24),p,dp(24));r.setBackgroundColor(Color.rgb(12,12,12));s.addView(r);setContentView(s);return r;}
 private void showAccount(){LinearLayout r=page();r.addView(t("Account",30));r.addView(t(prefs.getBoolean("guest",false)?"Currently watching as Guest":"No account connected",18));Button sign=b("SIGN IN WITH PHONE / QR");sign.setOnClickListener(v->showSignIn());r.addView(sign,new LinearLayout.LayoutParams(-1,dp(60)));Button yt=b("YOUTUBE ACCOUNT IN BROWSER");yt.setOnClickListener(v->openWeb("https://www.youtube.com/account"));r.addView(yt,new LinearLayout.LayoutParams(-1,dp(60)));Button back=b("← HOME");back.setOnClickListener(v->showHome());r.addView(back,new LinearLayout.LayoutParams(-1,dp(60)));sign.requestFocus();}
 private void showLocal(){LinearLayout r=page();r.addView(t("TRK Favorites",30));r.addView(t("Favorites are preserved locally. Thumbnail cards will be expanded in the next content-data build.",17));Button back=b("← HOME");back.setOnClickListener(v->showHome());r.addView(back,new LinearLayout.LayoutParams(-1,dp(60)));back.requestFocus();}
 private void showSettings(){LinearLayout r=page();r.addView(t("Settings",30));r.addView(t("TRK YouTube TV v"+VERSION+"\nAndroid "+Build.VERSION.RELEASE+" / API "+Build.VERSION.SDK_INT+"\nModel: "+Build.MANUFACTURER+" "+Build.MODEL+"\nMinimum Android: 4.4 / API 19",17));Button cookies=b("CLEAR YOUTUBE COOKIES");cookies.setOnClickListener(v->{CookieManager.getInstance().removeAllCookie();CookieManager.getInstance().removeSessionCookie();Toast.makeText(this,"Cookies cleared",0).show();});r.addView(cookies,new LinearLayout.LayoutParams(-1,dp(60)));Button welcome=b("PROFILE / START SCREEN");welcome.setOnClickListener(v->showWelcome());r.addView(welcome,new LinearLayout.LayoutParams(-1,dp(60)));Button back=b("← HOME");back.setOnClickListener(v->showHome());r.addView(back,new LinearLayout.LayoutParams(-1,dp(60)));cookies.requestFocus();}
 private void destroyWeb(){if(web!=null){try{web.stopLoading();web.destroy();}catch(Throwable e){}web=null;}}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else showHome();}
 @Override protected void onDestroy(){destroyWeb();super.onDestroy();}
}
