plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tvrepairkathmandu.trkyoutube'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tvrepairkathmandu.trkyoutube'
        minSdk 19
        targetSdk 35
        versionCode 7
        versionName '0.5.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
